### ISSUE TITLE
Installation instructions don't work out of the box when using zsh

### ISSUE THREAD

**Issue by mcreenan** [astronomer/telescope#147]
When running the installation steps in the zsh shell, the pip install command will fail because of the square brackets. 

What happens:
```
> python -m pip install telescope[charts] --find-links https://github.com/astronomer/telescope/releases/
zsh: no matches found: telescope[charts]
```

To make it work, you have to quote the package name:

```
python -m pip install 'telescope[charts]' --find-links https://github.com/astronomer/telescope/releases/
```

**Comment by fritz-astronomer** [comment]
thanks!
https://github.com/astronomer/telescope/commit/66e2040e13328dcec00113a7acbea4384477897c
