### ISSUE TITLE
DAG Stats rollup level feature

### ISSUE THREAD

**Issue by JasonVoss** [astronomer/telescope#188]
Request is to have a rollup of the Usage Stats to the Dag Level.  All of the stats are counted at the task level.  It would be nice to also know successful and failed DAG runs for the 1, 7, 30, 365, and All days .   This could (easily ?) be added to the Usage Stats report, since it is basically the same information, but it allows us to count against the DAG runs instead of the task runs within a DAG.  I suggest adding keys to the existing usage stats report.  alternatively, it could also exist in the dags report, but it probably belongs in usage stats

"dag_id": "dag_id_name",
"1_days_success": 5,
. . . <add the following>
"dag_rollup_1_days_success": 1

**Comment by fritz-astronomer** [comment]
I like it 👍 feel free to PR - if not there might be some other work incoming for the report and this could go along as well

**Comment by fritz-astronomer** [comment]
closed via telescope 3.2.0 - thanks so much for the contribution and apologies for the delays!
